version: '3.8'

services:
  mailpit:
    image: axllent/mailpit
    network_mode: "host"
    environment:
      MP_MAX_MESSAGES: 500
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"

  localstack:
    image: localstack/localstack:4.0.0
    network_mode: "host"
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
      EXTRA_CORS_ALLOWED_ORIGINS: "http://localhost:8080"
