env = "prod"
env = ${?ADOPTU_ENV}

ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.adoptu.ApplicationKt.module ]
    }
}

db {
    dev {
        postgres {
            driver = "org.postgresql.Driver"
            url = "jdbc:postgresql://localhost:5432/adoptu"
            user = "adoptu"
            password = "Ad0ptU"
        }
    }

    prod {
        postgres {
            driver = "org.postgresql.Driver"
            url = "jdbc:postgresql://localhost:5432/adoptu"
            url = ${?ADOPTU_DB_URL}
            user = "adoptu"
            user = ${?ADOPTU_DB_USER}
            password = "Ad0ptU"
            password = ${?ADOPTU_DB_PASSWORD}
        }
    }
}

storage {
    dev {
        bucket = "adoptu-pets"
        region = "us-east-1"
        endpoint = "http://localhost:4566"
        path_style_access = true
    }

    prod {
        bucket = ${?ADOPTU_S3_BUCKET}
        bucket = "adoptu-pets"
        region = ${?ADOPTU_S3_REGION}
        region = "us-east-1"
        endpoint = ${?ADOPTU_S3_ENDPOINT}
        path_style_access = ${?ADOPTU_S3_PATH_STYLE_ACCESS}
        path_style_access = false
    }
}

email {
    host = "localhost"
    host = ${?SMTP_HOST}
    port = 587
    port = ${?SMTP_PORT}
    username = ${?SMTP_USERNAME}
    password = ${?SMTP_PASSWORD}
    from = "noreply@adopt-u.com"
    from = ${?SMTP_FROM}
}

ses {
    region = "us-east-1"
    region = ${?AWS_REGION}
    endpoint = ${?AWS_SES_ENDPOINT}
}

admin {
    email = "adopt-u@adopt-u.org"
    email = ${?ADOPTU_ADMIN_EMAIL}
    username = ${?ADOPTU_ADMIN_USERNAME}
}

webauthn {
    rpId = "localhost"
    rpId = ${?ADOPTU_WEB_AUTHN_RP_ID}
    rpName = "Adopt-U Pet Adoption"
    rpName = ${?ADOPTU_WEB_AUTHN_RP_NAME}
    origin = "http://localhost:8080"
    origin = ${?ADOPTU_WEB_AUTHN_ORIGIN}
}
