env = "prod"
env = ${?ADOPTU_ENV}

ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.adoptu.ApplicationKt.module ]
    }
}

db {
    dev {
        postgres {
            driver = "org.postgresql.Driver"
            url = "jdbc:postgresql://localhost:5432/adoptu"
            user = "adoptu"
            password = "Ad0ptU"
        }
    }

    prod {
        postgres {
            driver = "org.postgresql.Driver"
            url = "jdbc:postgresql://localhost:5432/adoptu"
            url = ${?ADOPTU_DB_URL}
            user = "adoptu"
            user = ${?ADOPTU_DB_USER}
            password = "Ad0ptU"
            password = ${?ADOPTU_DB_PASSWORD}
        }
    }
}

storage {
    dev {
        bucket = "adoptu-pets"
        region = "us-east-1"
        endpoint = "http://localhost:4566"
        path_style_access = true
    }

    prod {
        bucket = ${?ADOPTU_S3_BUCKET}
        bucket = "adoptu-pets"
        region = ${?ADOPTU_S3_REGION}
        region = "us-east-1"
        endpoint = ${?ADOPTU_S3_ENDPOINT}
        path_style_access = ${?ADOPTU_S3_PATH_STYLE_ACCESS}
        path_style_access = false
    }
}

email {
    host = ${?SMTP_HOST}
    port = ${?SMTP_PORT}
    username = ${?SMTP_USERNAME}
    password = ${?SMTP_PASSWORD}
    from = ${?SMTP_FROM}
    from = "noreply@adopt-u.com"
}
