package com.adoptu.common

import java.text.Normalizer

enum class Country(val displayName: String, val i18nKey: String) {
    AFGHANISTAN("Afghanistan", "country.afghanistan"),
    ALBANIA("Albania", "country.albania"),
    ALGERIA("Algeria", "country.algeria"),
    ARGENTINA("Argentina", "country.argentina"),
    ARMENIA("Armenia", "country.armenia"),
    AUSTRALIA("Australia", "country.australia"),
    AUSTRIA("Austria", "country.austria"),
    AZERBAIJAN("Azerbaijan", "country.azerbaijan"),
    BANGLADESH("Bangladesh", "country.bangladesh"),
    BELARUS("Belarus", "country.belarus"),
    BELGIUM("Belgium", "country.belgium"),
    BOLIVIA("Bolivia", "country.bolivia"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "country.bosnia"),
    BRAZIL("Brazil", "country.brazil"),
    BULGARIA("Bulgaria", "country.bulgaria"),
    CAMBODIA("Cambodia", "country.cambodia"),
    CAMEROON("Cameroon", "country.cameroon"),
    CANADA("Canada", "country.canada"),
    CHILE("Chile", "country.chile"),
    CHINA("China", "country.china"),
    COLOMBIA("Colombia", "country.colombia"),
    COSTA_RICA("Costa Rica", "country.costaRica"),
    CROATIA("Croatia", "country.croatia"),
    CUBA("Cuba", "country.cuba"),
    CZECH_REPUBLIC("Czech Republic", "country.czechia"),
    DENMARK("Denmark", "country.denmark"),
    DOMINICAN_REPUBLIC("Dominican Republic", "country.dominicanRepublic"),
    ECUADOR("Ecuador", "country.ecuador"),
    EGYPT("Egypt", "country.egypt"),
    EL_SALVADOR("El Salvador", "country.elSalvador"),
    ESTONIA("Estonia", "country.estonia"),
    ETHIOPIA("Ethiopia", "country.ethiopia"),
    FINLAND("Finland", "country.finnland"),
    FRANCE("France", "country.france"),
    GEORGIA("Georgia", "country.georgia"),
    GERMANY("Germany", "country.germany"),
    GHANA("Ghana", "country.ghana"),
    GREECE("Greece", "country.greece"),
    GUATEMALA("Guatemala", "country.guatemala"),
    HAITI("Haiti", "country.haiti"),
    HONDURAS("Honduras", "country.honduras"),
    HUNGARY("Hungary", "country.hungary"),
    ICELAND("Iceland", "country.iceland"),
    INDIA("India", "country.india"),
    INDONESIA("Indonesia", "country.indonesia"),
    IRAN("Iran", "country.iran"),
    IRAQ("Iraq", "country.iraq"),
    IRELAND("Ireland", "country.ireland"),
    ISRAEL("Israel", "country.israel"),
    ITALY("Italy", "country.italy"),
    JAMAICA("Jamaica", "country.jamaica"),
    JAPAN("Japan", "country.japan"),
    JORDAN("Jordan", "country.jordan"),
    KAZAKHSTAN("Kazakhstan", "country.kazakhstan"),
    KENYA("Kenya", "country.kenya"),
    KUWAIT("Kuwait", "country.kuwait"),
    LATVIA("Latvia", "country.latvia"),
    LEBANON("Lebanon", "country.lebanon"),
    LIBYA("Libya", "country.libya"),
    LITHUANIA("Lithuania", "country.lithuania"),
    LUXEMBOURG("Luxembourg", "country.luxembourg"),
    MALAYSIA("Malaysia", "country.malaysia"),
    MEXICO("Mexico", "country.mexico"),
    MOLDOVA("Moldova", "country.moldova"),
    MONGOLIA("Mongolia", "country.mongolia"),
    MONTENEGRO("Montenegro", "country.montenegro"),
    MOROCCO("Morocco", "country.morocco"),
    MYANMAR("Myanmar", "country.myanmar"),
    NEPAL("Nepal", "country.nepal"),
    NETHERLANDS("Netherlands", "country.netherlands"),
    NEW_ZEALAND("New Zealand", "country.newZealand"),
    NICARAGUA("Nicaragua", "country.nicaragua"),
    NIGERIA("Nigeria", "country.nigeria"),
    NORTH_KOREA("North Korea", "country.northKorea"),
    NORWAY("Norway", "country.norway"),
    PAKISTAN("Pakistan", "country.pakistan"),
    PANAMA("Panama", "country.panama"),
    PARAGUAY("Paraguay", "country.paraguay"),
    PERU("Peru", "country.peru"),
    PHILIPPINES("Philippines", "country.philippines"),
    POLAND("Poland", "country.poland"),
    PORTUGAL("Portugal", "country.portugal"),
    PUERTO_RICO("Puerto Rico", "country.puertoRico"),
    QATAR("Qatar", "country.qatar"),
    ROMANIA("Romania", "country.romania"),
    RUSSIA("Russia", "country.russia"),
    SAUDI_ARABIA("Saudi Arabia", "country.saudiArabia"),
    SERBIA("Serbia", "country.serbia"),
    SINGAPORE("Singapore", "country.singapore"),
    SLOVAKIA("Slovakia", "country.slovakia"),
    SLOVENIA("Slovenia", "country.slovenia"),
    SOUTH_AFRICA("South Africa", "country.southAfrica"),
    SOUTH_KOREA("South Korea", "country.southKorea"),
    SPAIN("Spain", "country.spain"),
    SRI_LANKA("Sri Lanka", "country.sriLanka"),
    SUDAN("Sudan", "country.sudan"),
    SWEDEN("Sweden", "country.sweden"),
    SWITZERLAND("Switzerland", "country.switzerland"),
    SYRIA("Syria", "country.syria"),
    TAIWAN("Taiwan", "country.taiwan"),
    THAILAND("Thailand", "country.thailand"),
    TUNISIA("Tunisia", "country.tunisia"),
    TURKEY("Turkey", "country.turkey"),
    UKRAINE("Ukraine", "country.ukraine"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "country.uae"),
    UNITED_KINGDOM("United Kingdom", "country.uk"),
    UNITED_STATES("United States", "country.usa"),
    URUGUAY("Uruguay", "country.uraguay"),
    UZBEKISTAN("Uzbekistan", "country.uzbekistan"),
    VENEZUELA("Venezuela", "country.venezuela"),
    VIETNAM("Vietnam", "country.vietnam"),
    YEMEN("Yemen", "country.yemen");

    companion object {
        private val byNormalizedName: Map<String, Country> = entries.associateBy { normalize(it.displayName) }

        fun fromDisplayName(raw: String?): Country? {
            if (raw.isNullOrBlank()) return null
            entries.firstOrNull { it.displayName == raw }?.let { return it }
            return byNormalizedName[normalize(raw)]
        }

        private fun normalize(value: String): String =
            Normalizer.normalize(value.trim(), Normalizer.Form.NFD)
                .replace(Regex("\\p{M}"), "")
                .lowercase()
    }
}
